export type ModuleDefinition={key:string;title:string;description:string;legacy?:string};
export type SystemDefinition={key:string;code:string;title:string;description:string;icon:string;tone:string;modules:ModuleDefinition[]};
const m=(key:string,title:string,description:string,legacy?:string):ModuleDefinition=>({key,title,description,legacy});
export const systems:SystemDefinition[]=[
 {key:'admin',code:'SYS-01',title:'後台管理系統',description:'人員、權限、場域、通知、稽核與版面設定。',icon:'/Inspection/assets/system-icons/admin-icon.png',tone:'cyan',modules:[m('users','人員帳號','啟用中與停用帳號、單位及角色。','admin.html#users'),m('permissions','角色權限','角色與各系統存取權限。','rbac.html'),m('locations','場域位置','市場、樓層、區域與巡檢位置。','locations.html'),m('audit','操作稽核','系統操作、資料存取與登入紀錄。','admin.html#audit'),m('alerts','資安告警','異常讀取、拒絕存取與安全事件。','admin.html#security'),m('notices','通知中心','系統通知與處理狀態。','notices.html'),m('layouts','戰情版面','戰情儀表板版面與元件版本。','dashboard-builder.html'),m('cycles','巡檢週期','巡檢週期開啟、重置與週期歷史。','admin.html#cycles'),m('costs','費用統計','設備生命週期費用記錄與排名。','admin.html#costs'),m('locanalysis','位置分析','場域下鑽的巡檢異常與報修樞紐統計。','admin.html#locanalysis'),m('health','系統健康','前端程式錯誤與系統介接異常紀錄。','admin.html#syshealth')]},
 {key:'workorder',code:'SYS-02',title:'報修／派工／完工',description:'報修、派工、進度、附件、完工與分析。',icon:'/Inspection/assets/system-icons/maintenance-icon.png',tone:'amber',modules:[m('requests','報修案件','所有報修來源、故障描述與處理狀態。','workorder.html'),m('dispatch','派工作業','維修人員指派與進度追蹤。','dispatch.html'),m('orders','維修工單','工單生命週期與完工驗收。','admin.html#repairs'),m('attachments','維修附件','照片與報修附件索引。','workorder.html'),m('analytics','維修分析','案件趨勢、處理量與狀態分布。','analytics.html'),m('repairmap3d','報修3D平面圖','共用 3D 雲台圖資，查看報修點與空間位置。')]},
 {key:'guardpatrol',code:'SYS-03',title:'駐衛警巡檢系統',description:'巡邏點、打卡、排班、逾時通知與立體巡檢。',icon:'/Inspection/assets/system-icons/guardpatrol-icon.png',tone:'green',modules:[m('checkins','巡邏打卡','巡邏點簽到、座標與現場狀況。','patrolcheckin.html'),m('points','巡邏點清單','二維碼巡邏點與樓層位置。','patrollist.html'),m('shifts','巡檢排班','班別、人員與預定巡檢時段。','patrolshifts.html'),m('notifications','逾時推播','即時通訊與行動推播結果及失敗原因。','patrol-notifications.html'),m('records','設備巡檢','設備運轉狀態與異常紀錄。','guardpatrol.html'),m('map3d','立體巡檢雲臺','巡檢點與立體樓層關聯。','guardpatrol3d.html')]},
 {key:'handover',code:'SYS-04',title:'電子交接簿',description:'班別交接、設備概況、異常與待辦。',icon:'/Inspection/assets/system-icons/handover-icon.png',tone:'violet',modules:[m('records','交接紀錄','各班交接內容、簽核與時間。','handover.html'),m('open-items','未結事項','跨班延續的異常與待辦。','handover.html#open'),m('equipment','設備概況','交接時的設備運轉摘要。','handover.html#equipment')]},
 {key:'equipment',code:'SYS-05',title:'設備建置系統',description:'設備主檔、保養、履歷、合約、文件、成本與監控。',icon:'/Inspection/assets/system-icons/equipment-icon.png',tone:'cyan',modules:[m('assets','設備主檔','資產碼、規格、樓層與設備狀態。','equipment.html'),m('plans','保養排程','週期、下次日期與負責人。','equipment.html#plans'),m('records','維修履歷','保養與維修處理歷程。','equipment.html#records'),m('contracts','維護合約','廠商、期間與合約狀態。','equipment.html#contracts'),m('documents','設備文件','操作手冊、圖說與程式文件索引。','equipment.html#documents'),m('costs','年度成本','設備年度維護與採購成本。','equipment.html#costs'),m('monitoring','中央監控','監控點位與設備事件。','equipment.html#integration'),m('materials','材料主檔','設備材料與分類。','materials-archived.html')]},
 {key:'structuremap',code:'SYS-06',title:'專案關係與設備圖臺',description:'區域、標記、平面圖、立體樓層與模型。',icon:'/Inspection/assets/system-icons/settings-icon.png',tone:'violet',modules:[m('areas','區域位置表','樓層空間、面積與用途。','arealist.html'),m('markers','整合標記系統','平面圖標記與位置定位，設備、空間、巡邏點與報修點。','b1_integrated_marker_system.html'),m('floor2d','平面樓層圖','高解析度樓層平面圖。','b1plan.html'),m('floor3d','3D模型圖','統一 3D 立體模型資料來源，供後續多系統介接應用。','floor3d.html'),m('models','圖資專案設定','3D 建模系統是唯一圖資來源，供平面圖、3D 圖、標記與巡檢雲臺共用。','modeler.html'),m('relations','專案關係圖','子系統與資料庫關係。','structure_map.html')]},
 {key:'vehicle',code:'SYS-07',title:'公務車派車管理',description:'申請、核可、車輛、駕駛與行車紀錄。',icon:'/Inspection/assets/system-icons/vehicle-dispatch-icon-v4.png',tone:'amber',modules:[m('requests','派車申請','派車申請與多階段核可。','vehicle-dispatch.html'),m('vehicles','公務車輛','車號、狀態與里程。','vehicle-dispatch.html#vehicles'),m('drivers','駕駛人員','可指派駕駛與啟用狀態。','vehicle-dispatch.html#drivers'),m('managers','派車管理員','派車管理與授權人員。','vehicle-dispatch.html#managers'),m('logs','派車紀錄','狀態變更與行車歷程。','vehicle-dispatch.html#logs')]},
 {key:'meetingroom',code:'SYS-08',title:'會議室預約系統',description:'會議室、預約、變更申請與提醒。',icon:'/Inspection/assets/system-icons/meeting-room-icon-v3.png',tone:'green',modules:[m('bookings','會議預約','預約、報到與使用狀態。','meetingroom.html'),m('changes','變更申請','改期與取消申請。','meetingroom.html#changes'),m('notifications','預約提醒','到期提醒與通知結果。','meetingroom.html#notifications'),m('rooms','會議室主檔','會議室容量、位置與啟用狀態。','meetingroom.html#rooms')]},
 {key:'officialdocs',code:'SYS-09',title:'公文傳送系統',description:'公文送出、依序會辦、陳核、核決與原申請人收訖紀錄。',icon:'/Inspection/assets/system-icons/handover-icon.png',tone:'cyan',modules:[m('routing','公文傳送','以部／室為單位傳送、收文、簽收與核決。','official-document-routing')]},
];
export function findSystem(key:string){return systems.find(system=>system.key===key)}
export function findModule(systemKey:string,moduleKey:string){return findSystem(systemKey)?.modules.find(module=>module.key===moduleKey)}
export const allModuleParams=systems.flatMap(system=>system.modules.map(module=>({system:system.key,module:module.key})));
