(function(){
  'use strict';
  const db=createDb();
  const card=document.getElementById('card');
  const SUPA_URL=window.SUPA_URL;
  const SUPA_KEY=window.SUPA_KEY;
  function withTimeout(promise,ms){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('登入狀態確認逾時')),ms))]);}
  function makeId(){if(globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function')return globalThis.crypto.randomUUID();return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16);});}

  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
  function fmt(value){const d=new Date(value);const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}/${p(d.getMonth()+1)}/${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`;}
  function errorText(error){const code=String(error?.code||'');const message=String(error?.message||error||'');if(code==='mfa_factor_name_conflict'||/friendly name.*already exists/i.test(message))return '先前的驗證器設定尚未完成，系統將重新建立';if(code==='mfa_required')return '請先完成巡檢安全驗證後再簽到';if(/network|fetch|offline/i.test(message))return '網路連線失敗，巡檢簽到需要即時連線，請恢復網路後重試';if(/expired|invalid|jwt/i.test(message))return '登入狀態已失效，請重新登入';return message||'操作失敗，請稍後再試';}
  function showState(icon,iconClass,title,sub,backHref,backLabel){card.innerHTML=`<div class="icon ${iconClass}">${icon}</div><h1>${esc(title)}</h1><div class="sub">${esc(sub)}</div><a class="btn" href="${esc(backHref||'patrollist.html')}">← ${esc(backLabel||'返回巡檢')}</a>`;}
  function cachedProfile(session){let profile=null;try{profile=window.SystemUserProfile?.read?.()||null;}catch(_e){}return {user_id:profile?.user_id||null,name:profile?.name||sessionStorage.getItem('user_name')||session.user.user_metadata?.name||session.user.email||'巡檢人員'};}
  async function getProfile(session){const fallback=cachedProfile(session);try{const data=await window.SystemAuth.loadProfile(db);return data||fallback;}catch(_e){return fallback;}}
  async function getPoint(type,id){
    if(!navigator.onLine)throw new Error('目前離線');
    if(type==='marker'){const {data,error}=await db.from('plan_markers').select('marker_id,floor_id,label,kind,status').eq('marker_id',id).single();if(error)throw error;if(!data||data.kind!=='patrol'||data.status!=='active')return {invalid:true};return {label:data.label,floor_id:data.floor_id};}
    const {data,error}=await db.from('floor_spaces').select('space_id,floor,space_name,status').eq('space_id',id).single();if(error)throw error;if(!data||data.status&&data.status!=='active')return {invalid:true};return {label:data.space_name,floor_id:data.floor};
  }
  function mfaApi(){return db.auth&&db.auth.mfa?db.auth.mfa:null;}
  async function verifyMfaFactor(factorId,code){const api=mfaApi();if(!api)throw new Error('目前系統尚未啟用多因素驗證，請聯絡管理員');const challenge=await api.challenge({factorId});if(challenge.error)throw challenge.error;const result=await api.verify({factorId,challengeId:challenge.data.id,code:String(code||'').replace(/\D/g,'').slice(0,8)});if(result.error)throw result.error;const current=await db.auth.getSession();if(current.data?.session&&window.PatrolSessionBridge)window.PatrolSessionBridge.save(current.data.session);}
  async function requireMfa(backHref,backLabel){
    const api=mfaApi();if(!api){showState('⚠','err','無法進行安全驗證','系統尚未啟用巡檢多因素驗證，請聯絡管理員',backHref,backLabel);return false;}
    let aal;try{aal=await api.getAuthenticatorAssuranceLevel();if(aal?.error)throw aal.error;}catch(error){showState('⚠','err','安全驗證失敗',errorText(error),backHref,backLabel);return false;}
    const level=aal?.data||aal;if(level?.currentLevel==='aal2')return true;
    let factors;try{factors=await api.listFactors();if(factors?.error)throw factors.error;}catch(error){showState('⚠','err','安全驗證失敗',errorText(error),backHref,backLabel);return false;}
    const factorName='巡檢手機驗證';const allFactors=factors?.data?.all||[];const verified=(factors?.data?.totp||[]).find(f=>f.status==='verified');let setup=null,resetNotice='';
    if(!verified){const staleFactors=allFactors.filter(f=>f.factor_type==='totp'&&f.status!=='verified'&&f.friendly_name===factorName);for(const stale of staleFactors){const removed=await api.unenroll({factorId:stale.id});if(removed.error){showState('⚠','err','無法重設驗證器','先前的驗證器設定尚未完成，系統將重新建立',backHref,backLabel);return false;}}if(staleFactors.length)resetNotice='先前的驗證器設定尚未完成，系統將重新建立';const enrolled=await api.enroll({factorType:'totp',friendlyName:factorName});if(enrolled.error){showState('⚠','err','無法建立驗證器',errorText(enrolled.error),backHref,backLabel);return false;}setup=enrolled.data;}
    return new Promise(resolve=>{
      card.innerHTML=`<div class="icon load">⌁</div><h1>巡檢安全驗證</h1><div class="sub">完成一次性驗證碼後，系統才會送出本次簽到</div><div class="mfa-box">${resetNotice?`<div class="mfa-help">${esc(resetNotice)}</div>`:''}${setup?`<div class="mfa-help">請用 Microsoft Authenticator、Google Authenticator 或其他 TOTP App 掃描下方 QR Code。</div><img class="mfa-qr" alt="多因素驗證 QR Code" src="${esc(setup.totp?.qr_code||'')}"><div class="mfa-secret">設定金鑰：<code>${esc(setup.totp?.secret||'')}</code></div>`:''}<label class="mfa-label" for="mfaCode">六位數驗證碼</label><input class="mfa-code" id="mfaCode" inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9]{6}" placeholder="請輸入 6 位數字"><div class="mfa-error" id="mfaError" hidden></div></div><button class="btn" id="mfaSubmit" type="button">驗證後簽到</button><a class="btn secondary" href="${esc(backHref)}">← ${esc(backLabel)}</a>`;
      const input=document.getElementById('mfaCode');const submit=document.getElementById('mfaSubmit');const errorBox=document.getElementById('mfaError');const factorId=setup?.id||verified?.id;
      const submitCode=async()=>{const code=String(input.value||'').trim();if(!/^\d{6}$/.test(code)){errorBox.hidden=false;errorBox.textContent='請輸入 6 位數字驗證碼';input.focus();return;}submit.disabled=true;submit.textContent='驗證中…';errorBox.hidden=true;try{await verifyMfaFactor(factorId,code);resolve(true);}catch(error){submit.disabled=false;submit.textContent='驗證後簽到';errorBox.hidden=false;errorBox.textContent='驗證碼錯誤或已過期，請重新輸入';input.select();}};
      submit.addEventListener('click',submitCode);input.addEventListener('keydown',event=>{if(event.key==='Enter')submitCode();});input.focus();
    });
  }
  async function secureCheckin(event){const {data:{session}}=await db.auth.getSession();if(!session)throw Object.assign(new Error('登入狀態已失效'),{code:'invalid_session'});const response=await fetch(`${SUPA_URL}/functions/v1/patrol-checkin`,{method:'POST',headers:{apikey:SUPA_KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(event),cache:'no-store'});const body=await response.json().catch(()=>({}));if(!response.ok||body.ok===false){const error=new Error(body.message||'巡檢簽到失敗');error.code=body.code||`http_${response.status}`;error.event=body.event;throw error;}return body;}
  function renderSuccess(event,point,duplicate,backHref,backLabel){const pointLabel=event.target_type==='marker'?'巡檢點':'巡檢區域';const sourceLabel=event.checkin_source==='nfc'?'NFC 感應':'QR Code';card.innerHTML=`<div class="icon ok">✓</div><h1>${duplicate?'已完成簽到':'簽到成功'}</h1><div class="sub">${duplicate?'本巡檢點五分鐘內已有簽到紀錄，系統未重複寫入':'巡檢紀錄已通過後端驗證並成功送出'}</div><div class="detail"><div><span class="k">${pointLabel}</span><b>${esc(point.label)}</b></div><div><span class="k">樓層</span><b>${esc(point.floor_id)}</b></div><div><span class="k">人員</span><b>${esc(event.user_name)}</b></div><div><span class="k">掃描時間</span><b>${esc(fmt(event.checkin_at))}</b></div><div><span class="k">簽到方式</span><b>${sourceLabel}</b></div></div><a class="btn" href="${esc(backHref)}">← ${esc(backLabel)}</a><div class="hist" id="hist"></div>`;loadHistory(event.target_type,event.target_id,pointLabel);}
  async function loadHistory(type,id,pointLabel){const hist=document.getElementById('hist');if(!hist||!navigator.onLine)return;hist.innerHTML=`<div class="hist-t">本${esc(pointLabel)}最近簽到紀錄</div><div class="hist-empty">載入中…</div>`;try{const {data,error}=await db.from('checkin_logs').select('user_name,checkin_at').eq('target_type',type).eq('target_id',id).order('checkin_at',{ascending:false}).limit(10);if(error)throw error;const rows=(data||[]).map(r=>`<div class="hist-row"><span class="u">${esc(r.user_name||'')}</span><span>${esc(fmt(r.checkin_at))}</span></div>`).join('');hist.innerHTML=`<div class="hist-t">本${esc(pointLabel)}最近簽到紀錄</div>${rows||'<div class="hist-empty">尚無簽到紀錄</div>'}`;}catch(_e){hist.innerHTML='<div class="hist-error">暫時無法載入紀錄</div>';}}
  async function main(){
    const params=new URLSearchParams(location.search),markerId=params.get('marker'),spaceId=params.get('space'),source=params.get('source')==='nfc'?'nfc':'qr';const targetType=markerId?'marker':spaceId?'space':null,targetId=markerId||spaceId;if(!targetType){showState('⚠','err','無效的巡檢碼','掃描碼缺少巡檢點資料');return;}
    const backHref=targetType==='marker'?'patrollist.html':'arealist.html';const backLabel=targetType==='marker'?'返回巡檢列表':'返回區域列表';if(!navigator.onLine){showState('⚠','err','需要網路連線','巡檢簽到必須即時連線，請恢復網路後重試',backHref,backLabel);return;}
    const bridge=window.PatrolSessionBridge;const trusted=bridge&&bridge.read();if(!trusted){try{await withTimeout(db.auth.signOut({scope:'local'}),2000);}catch(_e){}location.href='login.html?redirect='+encodeURIComponent('patrolcheckin.html'+location.search);return;}let session;try{({data:{session}}=await withTimeout(db.auth.getSession(),5000));}catch(_e){}if(session&&trusted.user_id!==session.user.id){try{await withTimeout(db.auth.signOut({scope:'local'}),2000);}catch(_e){}session=null;}if(!session){const sub=card.querySelector('.sub');if(sub)sub.textContent='正在恢復兩小時內的巡檢登入狀態';try{session=await withTimeout(bridge.restore(db),10000);}catch(_e){bridge.clear();session=null;}}if(!session){location.href='login.html?redirect='+encodeURIComponent('patrolcheckin.html'+location.search);return;}
    const profile=await getProfile(session);let point;try{point=await getPoint(targetType,targetId);}catch(error){showState('⚠','err','讀取巡檢點失敗',errorText(error),backHref,backLabel);return;}if(point.invalid){showState('⚠','err','巡檢點無效','此掃描碼已停用或不存在',backHref,backLabel);return;}
    const mfaReady=await requireMfa(backHref,backLabel);if(!mfaReady)return;const event={checkin_id:makeId(),target_type:targetType,target_id:targetId,floor_id:point.floor_id,label:point.label,user_name:profile.name||'巡檢人員',checkin_at:new Date().toISOString(),checkin_source:source};try{const result=await secureCheckin(event);renderSuccess(result.event||event,point,!!result.duplicate,backHref,backLabel);}catch(error){if(error.code==='duplicate_recent'){renderSuccess(error.event||event,point,true,backHref,backLabel);return;}if(error.code==='patrol_session_expired'||error.code==='invalid_session'){if(window.PatrolSessionBridge)window.PatrolSessionBridge.clear();try{await db.auth.signOut({scope:'local'});}catch(_e){}location.href='login.html?redirect='+encodeURIComponent('patrolcheckin.html'+location.search);return;}showState('⚠','err','簽到失敗',errorText(error),backHref,backLabel);}
  }
  main();
})();
