import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { fixture,safeSchema } from './vehicle-tracking-safe-bootstrap.test.mjs';
const schema=readFileSync(new URL('../supabase/migrations/20260908213500_findtag_visible_sync.sql',import.meta.url),'utf8');
const incompleteSchema=readFileSync(new URL('../supabase/migrations/20260908220000_findtag_incomplete_visible_rows.sql',import.meta.url),'utf8');
assert.doesNotMatch(schema.replace(/--[^\r\n]*/g,''),/\bdrop\s+table\b|\bdelete\s+from\b|\btruncate\s+(?!on\b)/i);
const db=new PGlite();
const token='a'.repeat(64), other='b'.repeat(64);
const rows=[{device_label:'合成設備',address_text:'合成地址（非真實位置）',source_time_text:'2026-09-08 12:00:00'}];
const rpc=async(name,args)=> (await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as result`,args)).rows[0].result;
const cooldown=()=>db.exec(`reset role; update findtag_collectors set last_contact_at=null; set role anon`);
try{
  await db.exec(fixture); await db.exec(safeSchema); await db.exec(schema); await db.exec(schema);
  await db.exec(incompleteSchema);await db.exec(incompleteSchema);
  await db.exec(`set role authenticated; select set_config('test.admin','no',false)`);
  await assert.rejects(rpc('findtag_create_pairing',['合成桌機']),/只有/);
  await db.exec(`select set_config('test.admin','yes',false)`);
  const pair=await rpc('findtag_create_pairing',['合成桌機']);
  await db.exec('set role anon');
  await assert.rejects(db.exec('select * from findtag_visible_snapshots'),/permission denied/);
  await assert.rejects(db.exec('select * from findtag_collector_credentials'),/permission denied/);
  const redeemed=await rpc('findtag_redeem_pairing',[pair.pairing_code,token]);
  assert.equal(redeemed.collector_id,pair.collector_id);
  assert.deepEqual(await rpc('findtag_redeem_pairing',[pair.pairing_code,token]),redeemed);
  await assert.rejects(rpc('findtag_redeem_pairing',[pair.pairing_code,other]),/已使用/);
  await assert.rejects(rpc('findtag_ingest',[other,new Date(),JSON.stringify(rows),'readable']),/授權無效/);
  await assert.rejects(rpc('findtag_ingest',[token,new Date(),JSON.stringify([{...rows[0],latitude:25}]),'readable']),/不接受推估座標/);
  await assert.rejects(rpc('findtag_ingest',[token,new Date(),JSON.stringify(rows),'arbitrary error']),/狀態無效/);
  const first=await rpc('findtag_ingest',[token,new Date(),JSON.stringify(rows),'readable']);
  assert.equal(first.accepted,true);assert.equal(first.duplicate,false);
  await assert.rejects(rpc('findtag_ingest',[token,new Date(),JSON.stringify(rows),'readable']),/過於頻繁/);
  await cooldown();
  const second=await rpc('findtag_ingest',[token,new Date(),JSON.stringify(rows),'readable']);
  assert.equal(second.duplicate,true);assert.equal(first.snapshot_id,second.snapshot_id);
  await cooldown();
  const time=Date.now();
  const different=[{...rows[0],address_text:'另一合成地址'}];
  await rpc('findtag_ingest',[token,new Date(time+1000),JSON.stringify(different),'readable']);
  await cooldown();
  await rpc('findtag_ingest',[token,new Date(time+3000),JSON.stringify(rows),'readable']);
  await cooldown();
  await rpc('findtag_ingest',[token,new Date(time+2000),JSON.stringify(different),'readable',false]);
  await db.exec('reset role');
  const afterAba=(await db.query('select latest_snapshot_id,last_status from findtag_collectors')).rows[0];
  assert.equal(afterAba.latest_snapshot_id,first.snapshot_id);assert.equal(afterAba.last_status,'read_failed');
  await cooldown();
  await assert.rejects(rpc('findtag_ingest',[token,new Date(),JSON.stringify(rows),'read_failed']),/不可傳送/);
  await rpc('findtag_ingest',[token,null,null,'read_failed']);
  await db.exec('reset role');
  assert.equal((await db.query('select count(*)::int as n from findtag_visible_snapshots')).rows[0].n,2);
  assert.equal((await db.query('select count(*)::int as n from vehicle_location_points')).rows[0].n,0);
  for(const table of ['findtag_collectors','findtag_visible_snapshots','findtag_collector_credentials']){
    await assert.rejects(db.exec(`delete from ${table}`),/禁止刪除/);
    await assert.rejects(db.exec(`truncate ${table} cascade`),/禁止刪除/);
  }
  await db.exec(`set role authenticated; select set_config('test.access','no',false)`);
  assert.equal((await db.query('select count(*)::int as n from findtag_visible_snapshots')).rows[0].n,0);
  await db.exec(`select set_config('test.access','yes',false)`);
  assert.equal((await db.query('select count(*)::int as n from findtag_visible_snapshots')).rows[0].n,2);
  await assert.rejects(db.exec('select * from findtag_collector_credentials'),/permission denied/);
  await cooldown();
  const incomplete=[...rows,{device_label:rows[0].device_label,address_text:null,source_time_text:null}];
  const incompleteResult=await rpc('findtag_ingest',[token,new Date(Date.now()+5000),JSON.stringify(incomplete),'readable']);
  await db.exec('reset role');
  const saved=(await db.query('select observations from findtag_visible_snapshots where snapshot_id=$1',[incompleteResult.snapshot_id])).rows[0].observations;
  assert.equal(saved.length,2);assert.equal(saved.filter(row=>row.address_text===null).length,1);
  await cooldown();
  await assert.rejects(rpc('findtag_ingest',[token,new Date(),JSON.stringify([{device_label:'合成',address_text:null,source_time_text:'2026-09-08 12:00:00'}]),'readable']),/完整配對/);
  await db.exec('set role authenticated');
  await rpc('findtag_disable_collector',[pair.collector_id]);
  await db.exec('set role anon');
  await assert.rejects(rpc('findtag_ingest',[token,new Date(),JSON.stringify(rows),'readable']),/已停用/);
  console.log('FindTag 同步資料庫測試通過：管理權限、一次配對、冪等重試、去重、拒絕座標、匿名隔離、撤銷、永久保護。');
} finally{await db.close();}
